server.port=8080
spring.application.name=api-gateway

jwt.secret=${JWT_SECRET:educommerce-secret-key-for-jwt-token-generation-2024}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=lb://student-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/students/**,/auth/**,/courses/**,/enroll/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[1].id=attendance-service
spring.cloud.gateway.routes[1].uri=lb://attendance-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/attendance/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[2].id=result-service
spring.cloud.gateway.routes[2].uri=lb://result-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/results/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
